services:
  db:
    image: postgres:15
    container_name: invoice-db
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: invoice-redis
    ports:
    - "${REDIS_PORT}:6379"

volumes:
  db-data: